# Generated by Django 3.0.5 on 2023-03-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_feedback_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
